server:
  port: 10010 #服务端口
spring:
  application:
    name: zuul-service #指定服务名
zuul:
  prefix: /api # 添加路由前缀
  routes:
    user-service: # 这里是路由id，随意写
      path: /user-service/** # 这里是映射路径
      url: http://127.0.0.1:8081 # 映射路径对应的实际url地址
    user-consumer-feign:
      path: /user-consumer-feign/** # 这里是映射路径
      url: http://127.0.0.1:8085 # 映射路径对应的实际url地址
    file-consumer: # 这里是路由id，不能随意写
      path: /file-consumer/** # 这里是映射路径
      url: http://127.0.0.1:8088 # 映射路径对应的实际url地址
    file-server: # 这里是路由id，不能随意写
        path: /file-server/** # 这里是映射路径
        url: http://127.0.0.1:8089 # 映射路径对应的实际url地址
  ratelimit:
    key-prefix: user-consumer-feign #请求的key的前缀
    enabled: true
    behind-proxy: true #代理之后
    default-policy: #针对所有的路由配置的策略
      limit: 10 #请求数量限制
      quota: 1000 #请求时间限制
      refresh-interval: 60 # 刷新时间窗口的时间
      type:  #可选 限流方式
        - user
        - origin
        - url
eureka:
  client:
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期：5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1